import AppKit
import Observation
import SwiftUI
import UniformTypeIdentifiers

struct ClipboardItem: Identifiable, Codable, Hashable, Sendable {
    enum Kind: String, Codable, Sendable {
        case text, link, color, image, file
    }

    let id: UUID
    var kind: Kind
    /// Plain-text payload for text/link/color, a file path for image/file.
    var value: String
    var preview: String
    var sourceApp: String?
    var sourceBundleID: String?
    var createdAt: Date
    var isPinned: Bool

    var url: URL? {
        switch kind {
        case .link: URL(string: value)
        case .image, .file: URL(fileURLWithPath: value)
        default: nil
        }
    }

    var color: Color? {
        guard kind == .color else { return nil }
        return Color(hex: value)
    }

    var symbol: String {
        switch kind {
        case .text: "text.alignleft"
        case .link: "link"
        case .color: "paintpalette.fill"
        case .image: "photo"
        case .file: "doc"
        }
    }

    var kindLabel: String {
        switch kind {
        case .text: "Text"
        case .link: "Link"
        case .color: "Color"
        case .image: "Image"
        case .file: "File"
        }
    }
}

/// Watches the general pasteboard and keeps a searchable, local-only history.
@MainActor
@Observable
final class ClipboardStore {
    static let shared = ClipboardStore()

    private(set) var items: [ClipboardItem] = []
    var query: String = ""

    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount
    /// Set while Cowly itself writes to the pasteboard, so we skip our own echo.
    private var isWritingOurselves = false

    private init() {
        items = Disk.load([ClipboardItem].self, from: Paths.clipboardStore) ?? []
    }

    var filtered: [ClipboardItem] {
        let base = items.sorted { lhs, rhs in
            if lhs.isPinned != rhs.isPinned { return lhs.isPinned }
            return lhs.createdAt > rhs.createdAt
        }
        guard !query.isEmpty else { return base }
        return base.filter {
            $0.preview.localizedCaseInsensitiveContains(query)
                || $0.value.localizedCaseInsensitiveContains(query)
                || ($0.sourceApp ?? "").localizedCaseInsensitiveContains(query)
        }
    }

    // MARK: - Monitoring

    func start() {
        guard timer == nil else { return }
        let timer = Timer.scheduledTimer(withTimeInterval: 0.45, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        timer.tolerance = 0.15
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func poll() {
        guard Preferences.shared.clipboardEnabled else { return }
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount
        guard !isWritingOurselves else { isWritingOurselves = false; return }
        // Respect the community convention password managers use to opt out.
        let opaque: Set<String> = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"]
        if let types = pb.types, types.contains(where: { opaque.contains($0.rawValue) }) { return }

        guard let item = capture(from: pb) else { return }
        insert(item)
    }

    private func capture(from pb: NSPasteboard) -> ClipboardItem? {
        let app = NSWorkspace.shared.frontmostApplication
        let appName = app?.localizedName
        let bundleID = app?.bundleIdentifier
        // Never record what Cowly itself just copied out of the history.
        if bundleID == Bundle.main.bundleIdentifier { return nil }

        if let urls = pb.readObjects(forClasses: [NSURL.self]) as? [URL], let first = urls.first, first.isFileURL {
            return ClipboardItem(
                id: UUID(), kind: .file, value: first.path(percentEncoded: false),
                preview: first.lastPathComponent, sourceApp: appName, sourceBundleID: bundleID,
                createdAt: .now, isPinned: false
            )
        }

        if let string = pb.string(forType: .string)?.trimmingCharacters(in: .whitespacesAndNewlines), !string.isEmpty {
            let kind: ClipboardItem.Kind
            if string.hexColorValue != nil {
                kind = .color
            } else if let url = URL(string: string), url.scheme?.hasPrefix("http") == true {
                kind = .link
            } else {
                kind = .text
            }
            let value = kind == .color ? (string.hexColorValue ?? string) : string
            return ClipboardItem(
                id: UUID(), kind: kind, value: value,
                preview: String(string.prefix(400)), sourceApp: appName, sourceBundleID: bundleID,
                createdAt: .now, isPinned: false
            )
        }

        if let image = NSImage(pasteboard: pb), let path = persistImage(image) {
            return ClipboardItem(
                id: UUID(), kind: .image, value: path,
                preview: "\(Int(image.size.width))×\(Int(image.size.height))",
                sourceApp: appName, sourceBundleID: bundleID, createdAt: .now, isPinned: false
            )
        }
        return nil
    }

    private func persistImage(_ image: NSImage) -> String? {
        guard let tiff = image.tiffRepresentation,
              let rep = NSBitmapImageRep(data: tiff),
              let png = rep.representation(using: .png, properties: [:]) else { return nil }
        let url = Paths.clipboardAssets.appendingPathComponent("\(UUID().uuidString).png")
        guard (try? png.write(to: url)) != nil else { return nil }
        return url.path(percentEncoded: false)
    }

    private func insert(_ item: ClipboardItem) {
        // Collapse repeats of the same content instead of stacking duplicates.
        if let index = items.firstIndex(where: { $0.value == item.value && $0.kind == item.kind }) {
            var existing = items.remove(at: index)
            existing.createdAt = item.createdAt
            items.insert(existing, at: 0)
        } else {
            items.insert(item, at: 0)
        }
        trim()
        persist()
    }

    private func trim() {
        let limit = max(20, Preferences.shared.clipboardLimit)
        guard items.count > limit else { return }
        let pinned = items.filter(\.isPinned)
        var unpinned = items.filter { !$0.isPinned }
        while pinned.count + unpinned.count > limit, let last = unpinned.popLast() {
            if last.kind == .image { try? FileManager.default.removeItem(atPath: last.value) }
        }
        items = (pinned + unpinned).sorted { $0.createdAt > $1.createdAt }
    }

    // MARK: - Actions

    func copy(_ item: ClipboardItem) {
        isWritingOurselves = true
        let pb = NSPasteboard.general
        pb.clearContents()
        switch item.kind {
        case .text, .link, .color:
            pb.setString(item.value, forType: .string)
        case .image, .file:
            if let url = item.url { pb.writeObjects([url as NSURL]) }
            if item.kind == .image, let url = item.url, let image = NSImage(contentsOf: url) {
                pb.writeObjects([image])
            }
        }
        lastChangeCount = pb.changeCount
        Haptics.tap(.generic)
    }

    /// Copies and then sends ⌘V to whatever app is in front.
    func paste(_ item: ClipboardItem) {
        copy(item)
        NotchViewModel.shared.close(force: true)
        Task {
            try? await Task.sleep(for: .milliseconds(140))
            KeyboardSimulator.sendCommandV()
        }
    }

    func togglePin(_ item: ClipboardItem) {
        guard let index = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[index].isPinned.toggle()
        persist()
    }

    func remove(_ item: ClipboardItem) {
        items.removeAll { $0.id == item.id }
        if item.kind == .image { try? FileManager.default.removeItem(atPath: item.value) }
        persist()
    }

    func clear() {
        for item in items where !item.isPinned {
            if item.kind == .image { try? FileManager.default.removeItem(atPath: item.value) }
        }
        items = items.filter(\.isPinned)
        persist()
    }

    func sendToTray(_ item: ClipboardItem) {
        switch item.kind {
        case .image, .file:
            if let url = item.url { TrayStore.shared.add(urls: [url]) }
        default:
            TrayStore.shared.add(text: item.value)
        }
    }

    private func persist() { Disk.save(items, to: Paths.clipboardStore) }
}

/// Posts a synthetic ⌘V into the current app so "Paste" actually pastes.
enum KeyboardSimulator {
    static func sendCommandV() {
        guard AXIsProcessTrusted() else {
            log.notice("Paste needs Accessibility permission; copied to the clipboard instead.")
            return
        }
        let source = CGEventSource(stateID: .combinedSessionState)
        source?.setLocalEventsFilterDuringSuppressionState(
            [.permitLocalMouseEvents, .permitSystemDefinedEvents],
            state: .eventSuppressionStateSuppressionInterval
        )
        let keyV: CGKeyCode = 0x09
        let down = CGEvent(keyboardEventSource: source, virtualKey: keyV, keyDown: true)
        let up = CGEvent(keyboardEventSource: source, virtualKey: keyV, keyDown: false)
        down?.flags = .maskCommand
        up?.flags = .maskCommand
        down?.post(tap: .cgAnnotatedSessionEventTap)
        up?.post(tap: .cgAnnotatedSessionEventTap)
    }
}

extension String {
    /// Returns a normalised `#RRGGBB` string when the text looks like a colour.
    var hexColorValue: String? {
        let trimmed = trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmed.count == 7 || trimmed.count == 4 || trimmed.count == 9 else { return nil }
        guard trimmed.hasPrefix("#") else { return nil }
        let hex = trimmed.dropFirst()
        guard hex.allSatisfy({ $0.isHexDigit }) else { return nil }
        return trimmed.uppercased()
    }
}

extension Color {
    init?(hex: String) {
        var value = hex.trimmingCharacters(in: .whitespacesAndNewlines)
        if value.hasPrefix("#") { value.removeFirst() }
        if value.count == 3 { value = value.map { "\($0)\($0)" }.joined() }
        guard value.count == 6 || value.count == 8, let int = UInt64(value, radix: 16) else { return nil }
        let r, g, b, a: Double
        if value.count == 6 {
            r = Double((int >> 16) & 0xFF) / 255
            g = Double((int >> 8) & 0xFF) / 255
            b = Double(int & 0xFF) / 255
            a = 1
        } else {
            r = Double((int >> 24) & 0xFF) / 255
            g = Double((int >> 16) & 0xFF) / 255
            b = Double((int >> 8) & 0xFF) / 255
            a = Double(int & 0xFF) / 255
        }
        self.init(.sRGB, red: r, green: g, blue: b, opacity: a)
    }
}
